Init:
  unstash: []
  stashes:
    - name: "source"
      includes: "**/*"
      excludes: ".pipeline/**"

'Pull-Request Voting':
  unstash:
    - source
  stashes: []

Build:
  unstash:
    - source
  stashes: []

Integration:
  unstash:
    - source
    - buildResult
  stashes: []

Acceptance:
  unstash:
    - buildResult
    - deployDescriptor
    - buildDescriptor
  stashes: []

Performance:
  unstash:
    - source
    - buildResult
  stashes: []

Release:
  unstash:
    - buildDescriptor
    - buildResult
    - deployDescriptor
  stashes: []
