steps:
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
    owner: 'HoffmannThomas'
    repository: 'jenkins-library'
    releaseBodyHeader: ''
  githubCreatePullRequest:
    base: master
    owner: 'HoffmannThomas'
    repository: 'jenkins-library'
    labels:
      - 'REVIEW'
      - 'go-piper'
    assignees:
      - 'HoffmannThomas'
